version: "3.8"

services:

  configserver:
    image: gagansharma2717/configuration_server:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - yeezybank-network

  accounts:
    image: gagansharma2717/accounts_service:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - yeezybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: gagansharma2717/loans_service:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - yeezybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: gagansharma2717/cards_service:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - yeezybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  yeezybank-network: